{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"AMB_Bricks_Expance_Sheet\",\"Kacha_Load_Sheet\",\"Others_sales\",\"Unload_table\",\"Vata_Sales\",\"_A Measures\",\"SD_Name\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "extendedProperties": [
      {
        "name": "SQLBI_BRAVO_ManageDatesConfiguration",
        "type": "json",
        "value": {
          "name": "Config-06",
          "autoNaming": 1,
          "autoScan": 127,
          "dateAvailable": true,
          "dateEnabled": true,
          "dateReferenceTableName": "DateAutoTemplate",
          "dateReferenceTableValidation": 1,
          "dateTableName": "Date",
          "dateTableValidation": 1,
          "defaults": {
            "firstDayOfWeek": 6,
            "firstFiscalMonth": 11
          },
          "description": "Custom fiscal calendar",
          "exceptTablesColumns": [],
          "holidaysAvailable": true,
          "holidaysDefinitionTableName": "HolidaysDefinition",
          "holidaysDefinitionTableValidation": 0,
          "holidaysEnabled": false,
          "holidaysTableName": "Holidays",
          "holidaysTableValidation": 0,
          "isCurrent": false,
          "isCustom": false,
          "isoCountry": "US",
          "onlyTablesColumns": [],
          "targetMeasures": [
            "Expence",
            "Sales",
            "Unit Sold",
            "Unit Unload"
          ],
          "templateUri": "file:///C:/Users/WIN-11/AppData/Local/Bravo/.temp/ManageDates/Templates/Config-06.template.json",
          "timeIntelligenceAvailable": true,
          "timeIntelligenceEnabled": true
        }
      }
    ],
    "relationships": [
      {
        "name": "20627d2a-f4b5-1710-e784-6b040a482fab",
        "fromColumn": "Date",
        "fromTable": "AMB_Bricks_Expance_Sheet",
        "toColumn": "Date",
        "toTable": "New_date"
      },
      {
        "name": "832fa83b-fe97-cd00-a5fe-c3835019d86f",
        "fromColumn": "Date",
        "fromTable": "Kacha_Load_Sheet",
        "toColumn": "Date",
        "toTable": "New_date"
      },
      {
        "name": "9686e0ea-d67b-e004-016b-863ea269247a",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Date",
        "fromTable": "New_date",
        "toColumn": "Date",
        "toTable": "Others_sales"
      },
      {
        "name": "1740fc86-730a-90e6-746b-5880bb0cbdba",
        "fromColumn": "Date",
        "fromTable": "Unload_table",
        "toColumn": "Date",
        "toTable": "New_date"
      },
      {
        "name": "a1b10d0e-0a04-3c9c-e1a6-143f69c99cf4",
        "fromColumn": "Date",
        "fromTable": "Vata_Sales",
        "toColumn": "Date",
        "toTable": "New_date"
      },
      {
        "name": "18cee6a8-326f-6d0e-62e6-16e77fc36610",
        "fromColumn": "Sardar_name",
        "fromTable": "Kacha_Load_Sheet",
        "toColumn": "SD Name",
        "toTable": "SD_Name"
      },
      {
        "name": "99bb7486-8c8e-f589-e7e9-7809e616f0a6",
        "fromColumn": "Payment To",
        "fromTable": "AMB_Bricks_Expance_Sheet",
        "toColumn": "SD Name",
        "toTable": "SD_Name"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "AMB_Bricks_Expance_Sheet",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "259140b5-efde-4267-b5e8-5d658da6d6cc",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Receipt No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "28a7b5f5-ab76-47f8-af5b-93d76617c7c2",
            "sourceColumn": "Receipt No",
            "summarizeBy": "sum"
          },
          {
            "name": "Acc_Head",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49b43ec2-6dda-4a89-92d9-34021a4b55f7",
            "sourceColumn": "Acc_Head",
            "summarizeBy": "none"
          },
          {
            "name": "Sub_Head",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b035c74e-c538-4f83-a0e8-c204eca49f54",
            "sourceColumn": "Sub_Head",
            "summarizeBy": "none"
          },
          {
            "name": "Payment_for",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c3b0863-a836-4867-89d8-9141ef8f3909",
            "sourceColumn": "Payment_for",
            "summarizeBy": "none"
          },
          {
            "name": "Payment To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73cdb21c-a887-4e2f-9501-4213f6734617",
            "sourceColumn": "Payment To",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c68c787-6e80-437d-aa3c-e614c5325b2d",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "88838f0d-3589-4990-a693-ce0aca600a33",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Remarks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "028de10c-b746-43f1-89f5-eca3c477b01e",
            "sourceColumn": "Remarks",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cda9d48b-efea-4726-883d-79b0141d6ec0",
        "partitions": [
          {
            "name": "AMB_Bricks_Expance_Sheet",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\aa Dip Work\\_Vata Work\\BrickField-Sales-Cost-Tracking-Dashboard\\AMB_Vata23_24.xlsx\"), null, true),",
                "    AMB_Bricks_Expance_Sheet_Table = Source{[Item=\"AMB_Bricks_Expance_Sheet\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(AMB_Bricks_Expance_Sheet_Table,{{\"Date\", type date}, {\"Receipt No\", Int64.Type}, {\"Acc_Head\", type text}, {\"Sub_Head\", type text}, {\"Payment_for\", type any}, {\"Payment To\", type any}, {\"Quantity\", type any}, {\"Amount\", type any}, {\"Remarks\", type any}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([Amount] <> null)),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Amount\", Int64.Type}, {\"Date\", type date}, {\"Quantity\", Int64.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Kacha_Load_Sheet",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c669c26c-1b21-408a-9ffb-f7398f5cd5a4",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Production_Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5451e7f2-a4f6-448a-b78b-fb952d8a51a5",
            "sourceColumn": "Production_Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sardar_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ad3c0c7-ad1e-4398-b696-11d91e91b8ed",
            "sourceColumn": "Sardar_name",
            "summarizeBy": "none"
          },
          {
            "name": "Production_Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a28d25f9-b52c-4b01-a11c-78a9c070b401",
            "sourceColumn": "Production_Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Remarks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "562fff88-bca0-4e41-b2cb-9325ce61edae",
            "sourceColumn": "Remarks",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "92edcda6-5fa0-41d0-86c5-eb2f5bbc7c6b",
        "partitions": [
          {
            "name": "Kacha_Load_Sheet",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\aa Dip Work\\_Vata Work\\BrickField-Sales-Cost-Tracking-Dashboard\\AMB_Vata23_24.xlsx\"), null, true),",
                "    Kacha_Load_Sheet_Table = Source{[Item=\"Kacha_Load_Sheet\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Kacha_Load_Sheet_Table,{{\"Date\", type date}, {\"Production_Category\", type text}, {\"Sardar_name\", type text}, {\"Production_Amount\", Int64.Type}, {\"Remarks\", type any}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Others_sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81dbf062-03d6-43b9-a53f-e629c265f55a",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d5892eb-bc76-490a-8a2f-881dfa8424fe",
            "sourceColumn": "Address",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99ba83a7-01be-4bba-b4b2-bd7e81bac201",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8139b27d-f338-4fa2-8781-f6d0dcb89c91",
            "sourceColumn": "Quantity",
            "summarizeBy": "none"
          },
          {
            "name": "Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2327a0fe-cb35-4823-a15c-315f640a372a",
            "sourceColumn": "Rate",
            "summarizeBy": "none"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1bc509a7-a451-43c1-bab7-bd8070604e59",
            "sourceColumn": "Price",
            "summarizeBy": "none"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ee55f7e-e7c3-495d-ac52-cda7102fd915",
            "sourceColumn": "Discount",
            "summarizeBy": "none"
          },
          {
            "name": "Final Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8053d9de-f2bf-47f8-a3c7-ed1c6e13fe64",
            "sourceColumn": "Final Amount",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "31c36b3a-4e45-461d-81b9-7c354b0cca34",
        "partitions": [
          {
            "name": "Others_sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\aa Dip Work\\_Vata Work\\BrickField-Sales-Cost-Tracking-Dashboard\\AMB_Vata23_24.xlsx\"), null, true),",
                "    Others_sales_Table = Source{[Item=\"Others_sales\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Others_sales_Table,{{\"Date\", type any}, {\"Address\", type any}, {\"Product Name\", type any}, {\"Quantity\", type any}, {\"Rate\", type any}, {\"Price\", type any}, {\"Discount\", type any}, {\"Final Amount\", type any}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([Date] <> null))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Unload_table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "610276dc-a6c5-4822-8906-db3604e78d62",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Sardar_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1231d9f-121d-4b6a-bb95-61bbb6ed0cae",
            "sourceColumn": "Sardar_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "939bc138-40a5-41cc-9537-9efc7b1e5021",
            "sortByColumn": "Sort",
            "sourceColumn": "Product Category",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "460dc47b-6d9a-46ad-b75f-43127e57dce8",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c9b461ee-139c-403b-b063-a6120395230e",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "8a679aef-f85b-4f34-8d8a-a8c860719bc2",
        "partitions": [
          {
            "name": "Unload_table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\aa Dip Work\\_Vata Work\\BrickField-Sales-Cost-Tracking-Dashboard\\AMB_Vata23_24.xlsx\"), null, true),",
                "    Uuload_table_Table = Source{[Item=\"Unload_table\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Uuload_table_Table,{{\"Date\", type date}, {\"Sardar_Name\", type text}, {\"No_1\", Int64.Type}, {\"Picket\", Int64.Type}, {\"No_2\", Int64.Type}, {\"Kara\", Int64.Type}, {\"Goyra\", Int64.Type}, {\"No_3\", Int64.Type}, {\"Total\", Int64.Type}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([Sardar_Name] <> null)),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Total\"}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Removed Columns\", {\"Date\", \"Sardar_Name\"}, \"Attribute\", \"Value\"),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Unpivoted Other Columns\", each ([Value] <> 0)),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Filtered Rows1\",{{\"Date\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"Attribute\", \"Product Category\"}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Renamed Columns\", \"Custom\", each if [Product Category] = \"No_1\" then 1 else if [Product Category] = \"Picket\" then 2 else if [Product Category] = \"No_2\" then 3 else if [Product Category] = \"Kara\" then 4 else if [Product Category] = \"No_3\" then 5 else if [Product Category] = \"Goyra\" then 6 else null, type number),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Added Conditional Column\", each true),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Filtered Rows2\",{{\"Custom\", \"Sort\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Vata_Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Money Receipt No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "40d7f94a-83fc-4ef5-b5b4-e530f93ef8dc",
            "sourceColumn": "Money Receipt No",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b705b929-6128-40bc-a369-864eb28b6275",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8290f495-85fc-4a81-9de0-3dfd2ccbffd8",
            "sourceColumn": "Address",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bed62403-a52d-4cfa-8d06-3e9ecd978f80",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ref Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80cc22c0-9290-4023-87be-4986ae867a68",
            "sourceColumn": "Ref Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c9302a75-85a6-4213-9c81-d53c19f922f3",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "370932a0-fa15-459e-8de6-02cf378d2a20",
            "sourceColumn": "Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dbb8af6f-57ad-453f-8ea4-953d353a9bb5",
            "sourceColumn": "Actual Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6ba821d0-1235-4538-8324-7753aa25d00d",
            "sourceColumn": "Actual Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5438733c-ff87-4f86-981e-a0ccc5c2a51e",
            "sourceColumn": "Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "710dd379-ff49-4cd4-9672-c0738a016353",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Final Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "92511df6-127e-481d-9101-b0b14b4587d7",
            "sourceColumn": "Final Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Remarks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf0d2d67-46e4-4610-a4fc-5d566df58753",
            "sourceColumn": "Remarks",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "478e980b-6c1a-4ecd-8ea5-79e5aed2732f",
            "sortByColumn": "Sort",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56a45cf4-e125-4578-91af-e120d8476a8a",
            "sourceColumn": "Sort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6813c15b-261d-4eeb-9c78-eb1fd25f2182",
        "partitions": [
          {
            "name": "Vata_Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\aa Dip Work\\_Vata Work\\BrickField-Sales-Cost-Tracking-Dashboard\\AMB_Vata23_24.xlsx\"), null, true),",
                "    Vata_Sales_Table = Source{[Item=\"Vata_Sales\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Vata_Sales_Table,{{\"Money Receipt No\", Int64.Type}, {\"Date\", type date}, {\"Address\", type text}, {\"Product Name\", type text}, {\"Ref Unit\", type text}, {\"Quantity\", Int64.Type}, {\"Rate\", type number}, {\"Actual Rate\", type number}, {\"Actual Quantity\", Int64.Type}, {\"Price\", type number}, {\"Discount\", Int64.Type}, {\"Final Price\", type number}, {\"Remarks\", type any}, {\"Category\", type text}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Changed Type\",{{\"Product Name\", Text.Trim, type text}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Trimmed Text\",{{\"Date\", type date}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateAutoTemplate",
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Dates"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "DateAutoTemplate"
          },
          {
            "name": "SQLBI_CalendarType",
            "value": "Fiscal"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "Date, FiscalDate"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "m/d/yyyy",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "01e906e4-5029-4f95-8538-bd19c132bc4f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0fea8aec-9f71-4dc4-9f1a-9aaa418ba550",
            "sourceColumn": "[DateKey]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sequential Day Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "ManufacturingDate"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "645e841b-1b29-4f56-a456-0f9e8deb0196",
            "sourceColumn": "[Sequential Day Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month",
            "dataCategory": "Months",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b2e0865d-6494-42bc-8bf7-57139f692d2e",
            "sortByColumn": "Year Month Number",
            "sourceColumn": "[Year Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalMonths"
              }
            ],
            "dataCategory": "Months",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0f358269-8da9-4adc-9098-569838fb86f8",
            "sourceColumn": "[Year Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Year",
            "dataCategory": "Years",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9f2aac33-334b-4a69-8889-eed5038980c6",
            "sortByColumn": "Fiscal Year Number",
            "sourceColumn": "[Fiscal Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Year Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalYears"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "80f35aa0-919f-4cad-8919-bf5944feaaae",
            "sourceColumn": "[Fiscal Year Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Year Quarter",
            "dataCategory": "Quarters",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7f4a4912-6c23-48b9-973b-2fee244bb4e3",
            "sortByColumn": "Fiscal Year Quarter Number",
            "sourceColumn": "[Fiscal Year Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Year Quarter Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalQuarters"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9c24e7e0-06d0-4990-87c8-ad4541a16e61",
            "sourceColumn": "[Fiscal Year Quarter Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Quarter",
            "dataCategory": "QuarterOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "20d2853a-cb8c-4842-bb7a-50f8435753c8",
            "sourceColumn": "[Fiscal Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "dataCategory": "MonthOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a0cfbded-1b04-426e-a981-23816e5c07bf",
            "sortByColumn": "Fiscal Month Number",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Month Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalMonthOfYear"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "aca32795-f067-407a-a2fd-523983f064ce",
            "sourceColumn": "[Fiscal Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Month in Quarter Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalMonthOfQuarter"
              }
            ],
            "dataCategory": "MonthOfQuarter",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4e62bde3-5ad5-4ed0-ba31-de96db87a639",
            "sourceColumn": "[Fiscal Month in Quarter Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalDayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d6a07078-8482-419e-a67a-6603f05527d7",
            "sortByColumn": "Day of Week Number",
            "sourceColumn": "[Day of Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalDayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c96e0e1f-3222-4c62-bccc-9938e529fa12",
            "sourceColumn": "[Day of Week Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Month Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalDayOfMonth"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2e190438-5759-46eb-9e28-790a1b4580fb",
            "sourceColumn": "[Day of Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Fiscal Year Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalDayOfYear"
              }
            ],
            "dataCategory": "DayOfYear",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "405d7f46-ae1e-4acb-ab94-1d149dc19e64",
            "sourceColumn": "[Day of Fiscal Year Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateWithTransactions",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DateDuration"
              }
            ],
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3e14ad0e-cb29-4043-889e-10a5f2f69d99",
            "sourceColumn": "[DateWithTransactions]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Fiscal",
            "isHidden": true,
            "levels": [
              {
                "name": "Year",
                "column": "Fiscal Year",
                "lineageTag": "6154877b-fbf2-4848-9e35-a71beba09748",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Fiscal Year Quarter",
                "lineageTag": "640cc2a1-0f81-440b-b512-6522f58c7891",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Year Month",
                "lineageTag": "fc555cec-d145-4703-af61-30dc906a0e2e",
                "ordinal": 2
              }
            ],
            "lineageTag": "2952b0f1-9fa5-4843-b683-886d379599d6"
          }
        ],
        "isHidden": true,
        "lineageTag": "3d840d51-1cd0-4b62-adfb-11c3f09508c3",
        "partitions": [
          {
            "name": "DateAutoTemplate",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "--  ",
                "--     Configuration",
                "--  ",
                "VAR __FirstFiscalMonth = 11",
                "-- Fiscal year as Calendar Year of :",
                "-- 0 - First day of fiscal year",
                "-- 1 - Last day of fiscal year",
                "VAR __TypeStartFiscalYear = 1",
                "-- 0 = Sunday, 1 = Monday, ...",
                "VAR __FirstDayOfWeek = 6",
                "----------------------------------------",
                "VAR __IsStandardLocale = IF ( FORMAT( DATE( 2000, 1, 1 ), \"oooo\" ) = \"oooo\", TRUE, FALSE )",
                "VAR __MonthFormatString = IF( __IsStandardLocale, \"mmm\", \"ooo\" )",
                "VAR __OffsetFiscalYearBeforeMonth = IF ( __FirstFiscalMonth > 1, __TypeStartFiscalYear - 1, 0 )",
                "VAR __OffsetFiscalYearOnOrAfterMonth = IF ( __FirstFiscalMonth > 1, __TypeStartFiscalYear, 0 )",
                "VAR __DayFormatString = IF( __IsStandardLocale, \"ddd\", \"aaa\" )",
                "VAR __WeekDayCalculationType = IF ( __FirstDayOfWeek = 0, 7, __FirstDayOfWeek ) + 10",
                "VAR __Calendar = ",
                "    VAR __FirstYear = YEAR ( MINX ( { MIN ( 'AMB_Bricks_Expance_Sheet'[Date] ), MIN ( 'Kacha_Load_Sheet'[Date] ), MIN ( 'Unload_table'[Date] ), MIN ( 'Vata_Sales'[Date] ) }, ''[Value] ) )",
                "    VAR __LastYear =  YEAR ( MAXX ( { MAX ( 'AMB_Bricks_Expance_Sheet'[Date] ), MAX ( 'Kacha_Load_Sheet'[Date] ), MAX ( 'Unload_table'[Date] ), MAX ( 'Vata_Sales'[Date] ) }, ''[Value] ) )",
                "    RETURN CALENDAR (",
                "        DATE ( __FirstYear, 1, 1 ),",
                "        DATE ( __LastYear, 12, 31 )",
                "    )",
                "VAR __Step3 = ",
                "    GENERATE (",
                "        __Calendar,",
                "        VAR __LastTransactionDate = MAXX ( { MAX ( 'AMB_Bricks_Expance_Sheet'[Date] ), MAX ( 'Kacha_Load_Sheet'[Date] ), MAX ( 'Unload_table'[Date] ), MAX ( 'Vata_Sales'[Date] ) }, ''[Value] )",
                "        VAR __Date = [Date]",
                "        VAR __YearNumber = YEAR ( __Date )",
                "        VAR __MonthNumber = MONTH ( __Date )",
                "        VAR __DayOfMonthNumber = DAY ( __Date )",
                "        VAR __DateKey = __YearNumber * 10000 + __MonthNumber * 100 + __DayOfMonthNumber",
                "        VAR __FiscalYearNumber = __YearNumber + __OffsetFiscalYearOnOrAfterMonth * ( __FirstFiscalMonth > 1 && __MonthNumber >= __FirstFiscalMonth ) + __OffsetFiscalYearBeforeMonth * ( __FirstFiscalMonth > 1 && __MonthNumber < __FirstFiscalMonth )",
                "        VAR __FiscalMonthNumber = __MonthNumber - __FirstFiscalMonth + 1 + 12 * (__MonthNumber < __FirstFiscalMonth)",
                "        VAR __FiscalQuarterNumber = ROUNDUP ( __FiscalMonthNumber / 3, 0 )",
                "        VAR __FiscalYearQuarterNumber = CONVERT ( __FiscalYearNumber * 4 + __FiscalQuarterNumber - 1, INTEGER )",
                "        VAR __FiscalMonthInQuarterNumber = MOD ( __FiscalMonthNumber - 1, 3 ) + 1",
                "        VAR __WeekDay = FORMAT ( __Date, __DayFormatString )",
                "        VAR __WeekDayNumber = WEEKDAY ( __Date, __WeekDayCalculationType )",
                "        VAR __FirstDayOfYear = DATE ( __FiscalYearNumber - 1 * (__FirstFiscalMonth > 1), __FirstFiscalMonth, 1 )",
                "        VAR __FiscalYearDayNumber = ",
                "            SUMX (",
                "                CALENDAR ( __FirstDayOfYear, __Date ),",
                "                1 * ( MONTH ( ''[Date] ) <> 2 || DAY ( ''[Date] ) <> 29 )",
                "            )",
                "        RETURN ROW ( ",
                "            \"DateKey\", __DateKey,",
                "            \"Sequential Day Number\", INT ( __Date ),",
                "            \"Year Month\", FORMAT ( __Date, __MonthFormatString & \" yyyy\" ),",
                "            \"Year Month Number\", __YearNumber * 12 + __MonthNumber - 1,",
                "            \"Fiscal Year\", FORMAT ( __FiscalYearNumber, \"\\F\\Y 0000\" ),",
                "            \"Fiscal Year Number\", __FiscalYearNumber,",
                "            \"Fiscal Year Quarter\", FORMAT ( __FiscalQuarterNumber, \"\\F\\Q0\" ) & \"-\" & FORMAT ( __FiscalYearNumber, \"0000\" ),",
                "            \"Fiscal Year Quarter Number\", __FiscalYearQuarterNumber,",
                "            \"Fiscal Quarter\", FORMAT( __FiscalQuarterNumber, \"\\F\\Q0\" ),",
                "            \"Month\", FORMAT ( __Date, __MonthFormatString ),",
                "            \"Fiscal Month Number\", __FiscalMonthNumber,",
                "            \"Fiscal Month in Quarter Number\", __FiscalMonthInQuarterNumber,",
                "            \"Day of Week\", __WeekDay,",
                "            \"Day of Week Number\", __WeekDayNumber,",
                "            \"Day of Month Number\", __DayOfMonthNumber,",
                "            \"Day of Fiscal Year Number\", __FiscalYearDayNumber,",
                "            \"DateWithTransactions\", __Date <= __LastTransactionDate ",
                "        )",
                "    )",
                "RETURN",
                "    __Step3"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Dates"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "Date"
          },
          {
            "name": "SQLBI_CalendarType",
            "value": "Fiscal"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "Date, FiscalDate"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "m/d/yyyy",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "01ff817e-20b5-4c36-87b1-c6b5703c9a14",
            "sourceColumn": "DateAutoTemplate[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8ec9830c-a1b1-4776-bf73-2ffc9ce9b1a2",
            "sourceColumn": "DateAutoTemplate[DateKey]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sequential Day Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "ManufacturingDate"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "082ffc1b-d84f-4ab0-bd33-286d5a9d5277",
            "sourceColumn": "DateAutoTemplate[Sequential Day Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month",
            "dataCategory": "Months",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "60eceeab-d054-4f1d-9800-1d88e6924276",
            "sortByColumn": "Year Month Number",
            "sourceColumn": "DateAutoTemplate[Year Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalMonths"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Months",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f6106283-f77e-4e24-84be-ea0d2439fdbb",
            "sourceColumn": "DateAutoTemplate[Year Month Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Year",
            "dataCategory": "Years",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "db83b17f-1675-4fd9-b783-d4a5c0738aac",
            "sortByColumn": "Fiscal Year Number",
            "sourceColumn": "DateAutoTemplate[Fiscal Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Year Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalYears"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ca09459b-f24a-4494-9fd6-ad028465e0ba",
            "sourceColumn": "DateAutoTemplate[Fiscal Year Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Year Quarter",
            "dataCategory": "Quarters",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "67385ea8-d20a-4118-8e93-99610b7a601c",
            "sortByColumn": "Fiscal Year Quarter Number",
            "sourceColumn": "DateAutoTemplate[Fiscal Year Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Year Quarter Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalQuarters"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "21f6b450-c144-4a5f-a1b5-51de50fc06a2",
            "sourceColumn": "DateAutoTemplate[Fiscal Year Quarter Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Quarter",
            "dataCategory": "QuarterOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cf9bc231-e28c-4741-97ff-59d82a881669",
            "sourceColumn": "DateAutoTemplate[Fiscal Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "dataCategory": "MonthOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "94876f89-1fdd-43a4-a3fc-fa98ef0649a6",
            "sortByColumn": "Fiscal Month Number",
            "sourceColumn": "DateAutoTemplate[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Month Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalMonthOfYear"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9f1b5f18-7799-40bb-9187-8623d124be1f",
            "sourceColumn": "DateAutoTemplate[Fiscal Month Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Month in Quarter Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalMonthOfQuarter"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "MonthOfQuarter",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b4819b45-fb98-4c35-8f1b-f82756a372ed",
            "sourceColumn": "DateAutoTemplate[Fiscal Month in Quarter Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalDayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7e551afb-4a59-40bc-98cd-a9d598df2a18",
            "sortByColumn": "Day of Week Number",
            "sourceColumn": "DateAutoTemplate[Day of Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalDayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0e9c5a2e-9317-41b0-b113-919e716df45f",
            "sourceColumn": "DateAutoTemplate[Day of Week Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Month Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalDayOfMonth"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8c8d619c-aa98-46e9-a62f-46e844408ea9",
            "sourceColumn": "DateAutoTemplate[Day of Month Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Fiscal Year Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "FiscalDayOfYear"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "DayOfYear",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "25cd5bf2-95be-402c-8b5a-739d735efbae",
            "sourceColumn": "DateAutoTemplate[Day of Fiscal Year Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateWithTransactions",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DateDuration"
              }
            ],
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c32c0893-a596-4953-920e-4230ee55b782",
            "sourceColumn": "DateAutoTemplate[DateWithTransactions]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Fiscal",
            "levels": [
              {
                "name": "Year",
                "column": "Fiscal Year",
                "lineageTag": "b21db779-0218-46e6-bcc4-62a1e0262ed3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Fiscal Year Quarter",
                "lineageTag": "d80a9d7c-2503-4f6f-affa-77eca9acb6d9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Year Month",
                "lineageTag": "d059ef4c-5046-4ab1-ac08-4958f82fe1a1",
                "ordinal": 2
              }
            ],
            "lineageTag": "9e9c7c01-89c9-4c0b-b52d-f0df5c92911b"
          }
        ],
        "lineageTag": "19d73e2f-9c30-497b-8454-919a1f7dadac",
        "measures": [
          {
            "name": "_ShowValueForDates",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Monthly"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Fiscal"
              }
            ],
            "displayFolder": "Hidden Time Intelligence",
            "expression": [
              "",
              "VAR __LastDateWithData =",
              "    CALCULATE (",
              "        MAXX ( { MAX ( 'AMB_Bricks_Expance_Sheet'[Date] ), MAX ( 'Kacha_Load_Sheet'[Date] ), MAX ( 'Unload_table'[Date] ), MAX ( 'Vata_Sales'[Date] ) }, ''[Value] ),",
              "        REMOVEFILTERS ()",
              "    )",
              "VAR __FirstDateVisible =",
              "    MIN ( 'Date'[Date] )",
              "VAR __Result =",
              "    __FirstDateVisible <= __LastDateWithData",
              "RETURN",
              "    __Result"
            ],
            "isHidden": true,
            "lineageTag": "4302a623-367a-419c-adbc-550e57e0dd7c"
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": "DateAutoTemplate",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_A Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "ed28e673-3563-47e1-a6f0-b80f9d949ec9",
        "measures": [
          {
            "name": "Total Expense",
            "expression": "SUM(AMB_Bricks_Expance_Sheet[Amount])",
            "formatString": "#,0",
            "lineageTag": "39ce5621-388f-4414-83a9-251ea160ef06"
          },
          {
            "name": "Coal_Expence",
            "expression": "CALCULATE([Total Expense], AMB_Bricks_Expance_Sheet[Sub_Head]=\"Coal\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "208f025b-98cf-462a-87bb-07acca3d4d79"
          },
          {
            "name": "Sardar_Expence",
            "expression": "CALCULATE([Total Expense], AMB_Bricks_Expance_Sheet[Acc_Head]= \"SD_Payment\")",
            "formatString": "#,0",
            "lineageTag": "6b9b2b72-8a6d-4521-95c1-3413fdbe59f7"
          },
          {
            "name": "Offical Cost",
            "expression": "CALCULATE([Total Expense], AMB_Bricks_Expance_Sheet[Acc_Head]=\"Offical Cost\")",
            "formatString": "#,0",
            "lineageTag": "c7bdc014-0775-4076-8da2-4d9d6730494e"
          },
          {
            "name": "Total_Sales",
            "expression": "SUM(Vata_Sales[Final Price])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "91abb979-9473-4e75-8fee-2e3c819f2de2"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total_Sales]- [Total Expense]",
            "lineageTag": "7bce886d-6d1c-47d6-8c40-92cb624666f3"
          },
          {
            "name": "Final Production",
            "expression": "SUM(Unload_table[Value])",
            "formatString": "#,0",
            "lineageTag": "1b1644ee-0836-48cd-a8ac-1143aa581f35"
          },
          {
            "name": "Final Production %",
            "expression": [
              "",
              "VAR unload = [Final Production]",
              "VAR Total_unload = CALCULATE([Final Production], ALLSELECTED(Unload_table))",
              "VAR Result = DIVIDE(unload, Total_unload, 0)",
              "RETURN",
              "Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f0c905c7-6847-4709-94b7-ea464e236178"
          },
          {
            "name": "Xcavator_Expence",
            "expression": "CALCULATE([Total Expense], AMB_Bricks_Expance_Sheet[Acc_Head]=\"Xcavator\")",
            "formatString": "0",
            "lineageTag": "75b6336d-72e5-423d-9eca-1b7f6e8fd7ca"
          },
          {
            "name": "Sales %",
            "expression": [
              "",
              "DIVIDE([Total_Sales],",
              "    CALCULATE([Total_Sales], ALLSELECTED(Vata_Sales)),0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "493f2e8b-fd50-4996-ae3f-72692dc960bd"
          },
          {
            "name": "Total Unit Sold",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(Vata_Sales[Actual Quantity])",
            "lineageTag": "4894f485-d141-4a3e-9d26-a3ff5c5d97df"
          },
          {
            "name": "AVG Production Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Total Expense],[Final Production],0)",
            "lineageTag": "cd29d833-48d3-4ea1-914b-49d320a4ed2e"
          },
          {
            "name": "AVG Sales Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Total_Sales],[Total Unit Sold],0)",
            "lineageTag": "9b434768-12d6-42c6-91bc-03d017201611"
          },
          {
            "name": "Xcavator hour",
            "expression": "CALCULATE(SUM(AMB_Bricks_Expance_Sheet[Quantity]), AMB_Bricks_Expance_Sheet[Sub_Head]=\"Driver Bill\")",
            "formatString": "0",
            "lineageTag": "b849a98b-bbae-40ab-b5fa-c21e20fbccca"
          },
          {
            "name": "YTD Expense",
            "expression": [
              "",
              "CALCULATE( [Total Expense],",
              "DATESYTD(New_date[Date],\"10-31\")",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "144bf694-7373-44be-b6d4-63406d7b2ec2"
          },
          {
            "name": "YTD Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE( [Total_Sales],",
              "DATESYTD(New_date[Date],\"10-31\")",
              ")"
            ],
            "lineageTag": "f8c024f3-85eb-4f50-a48e-ff08982802bc"
          },
          {
            "name": "YTD Production",
            "expression": "CALCULATE([Final Production], DATESYTD(New_date[Date],\"10-31\"))",
            "formatString": "#,0",
            "lineageTag": "42d61cf2-7dee-47a3-9563-36a3dcbf8eae"
          },
          {
            "name": "Previous Year YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE(Parameter[Parameter Fields]) = \"Expense\", [PY Expence YTD],",
              "    SELECTEDVALUE(Parameter[Parameter Fields]) = \"Sales\", [PY Sales YTD],",
              "    SELECTEDVALUE(Parameter[Parameter Fields]) = \"Production\", [PY Production YTD],",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "70edc807-fcc5-4fc5-8765-aec0e155f93d"
          },
          {
            "name": "PY Sales YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Total_Sales], ",
              "    DATESYTD(",
              "        SAMEPERIODLASTYEAR('Date'[Date])",
              "    )",
              ")",
              ""
            ],
            "lineageTag": "f776b16c-af3f-4ea4-ac75-25df2400d589"
          },
          {
            "name": "PY Expence YTD",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Expense], ",
              "    DATESYTD(",
              "        SAMEPERIODLASTYEAR('Date'[Date])",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ab08a153-2bb5-46aa-a42c-44b4b2e76d89"
          },
          {
            "name": "PY Production YTD",
            "expression": [
              "",
              "CALCULATE(",
              "    [Final Production], ",
              "    DATESYTD(",
              "        SAMEPERIODLASTYEAR('Date'[Date])",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "01c1e14f-2be5-4be6-9564-c53a29819ccf"
          },
          {
            "name": "Labour_Cost",
            "expression": "CALCULATE([Total Expense], AMB_Bricks_Expance_Sheet[Acc_Head]=\"Labour\")",
            "formatString": "#,0",
            "lineageTag": "1259a630-c016-4c82-abf1-6f1c476fb9ae"
          },
          {
            "name": "Coal_Qty (Ton)",
            "expression": "CALCULATE(SUM(AMB_Bricks_Expance_Sheet[Quantity]),AMB_Bricks_Expance_Sheet[Sub_Head]=\"Coal\")",
            "formatString": "0",
            "lineageTag": "2adf2ac1-1276-4298-a391-d9640dfd1424"
          },
          {
            "name": "Kacha Production",
            "expression": "CALCULATE(SUM(Kacha_Load_Sheet[Production_Amount]), Kacha_Load_Sheet[Production_Category]=\"Kacha\")",
            "formatString": "#,0",
            "lineageTag": "db48a5bd-a0fa-44c6-8ebd-37ebb85578cd"
          },
          {
            "name": "Kacha Load",
            "expression": "CALCULATE(SUM(Kacha_Load_Sheet[Production_Amount]), Kacha_Load_Sheet[Production_Category]=\"Load\")",
            "formatString": "0",
            "lineageTag": "22e2282f-2f8c-4c4f-9c19-8a5789a5460e"
          },
          {
            "name": "Kacha Production Expense",
            "expression": "CALCULATE([Total Expense], AMB_Bricks_Expance_Sheet[Sub_Head]=\"Kacha_production\")",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "bf9b3f67-e3c0-4956-98d0-f9a7e733bbc6"
          },
          {
            "name": "Per 1K Kacha",
            "expression": "DIVIDE([Kacha Production Expense], [Kacha Production], 0) * 1000",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "7d343604-c969-4dbc-97c1-0bdde3264229"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "a1ba1365-ff95-4449-b4be-f1130a4a42c7"
          },
          {
            "name": "Load %",
            "expression": "DIVIDE([Kacha Load], [Kacha Production], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2f5a7012-021f-440c-91b7-6db1e23c69bd"
          },
          {
            "name": "Toal Load",
            "expression": "[Kacha Load] + 300000",
            "formatString": "0",
            "lineageTag": "9ff74acb-ca22-49e1-9d65-01cdaaf2115f"
          },
          {
            "name": "Production %",
            "expression": "DIVIDE([Final Production], [Toal Load], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1834a439-6451-4ada-83aa-a8969ef934bd"
          },
          {
            "name": "Load Expense",
            "expression": "CALCULATE([Total Expense], AMB_Bricks_Expance_Sheet[Sub_Head]=\"Load\")",
            "formatString": "0",
            "lineageTag": "ff8ffbfa-5eb1-427f-932e-f766660a781c"
          },
          {
            "name": "Per 1K Load",
            "expression": "DIVIDE([Load Expense], [Toal Load], 0) * 1000",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "539e1fe4-b25e-499a-90de-2ccb705c84cb"
          },
          {
            "name": "Total Unload expense",
            "expression": "CALCULATE([Total Expense], AMB_Bricks_Expance_Sheet[Sub_Head]=\"Unload\")",
            "formatString": "0",
            "lineageTag": "221e5ff6-5144-424a-ae5c-595ba923afa7"
          },
          {
            "name": "Per 1K Unload",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Total Unload expense], [Final Production], 0) *1000",
            "lineageTag": "12c08c26-d893-4fa2-8178-87d0142fc358"
          },
          {
            "name": "Kacha Load Loss",
            "expression": "1-[Load %]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4429f49b-7480-44aa-916f-d41840943408"
          },
          {
            "name": "Z_Roling_AVG Expense",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Period = ",
              "    DATESINPERIOD(",
              "        New_date[Date],",
              "        MAX(New_date[Date]),",
              "        -2,",
              "        MONTH",
              "    )",
              "",
              "VAR Total_Expense =",
              "    CALCULATE(",
              "        [Total Expense],",
              "        Period",
              "    )",
              "",
              "VAR Month_Count = ",
              "    DISTINCTCOUNT(New_date[Fiscal_month])  -- Or New_date[Month_no]",
              "",
              "VAR Result =",
              "    DIVIDE(Total_Expense, Month_Count)",
              "",
              "RETURN",
              "    Result",
              "",
              ""
            ],
            "lineageTag": "09231870-c4e2-4fbc-bd2f-cbdbea363a43"
          },
          {
            "name": "RollingAVG_Expense",
            "expression": [
              "",
              "VAR NumDays = 7",
              "VAR RollingSum = ",
              "    CALCULATE([Total Expense], ",
              "DATESINPERIOD(New_date[Date], LASTDATE(New_date[Date]), - NumDays, DAY))",
              "RETURN",
              "DIVIDE(RollingSum, NumDays)"
            ],
            "formatString": "#,0",
            "lineageTag": "96851db5-991c-4bf0-8b67-0daa167425b2"
          },
          {
            "name": "AVG Expense",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "AVERAGEx(AMB_Bricks_Expance_Sheet, AMB_Bricks_Expance_Sheet[Amount])",
            "isHidden": true,
            "lineageTag": "af882de5-3ba7-4de2-99ff-f0eda14f23eb"
          },
          {
            "name": "RollingAVG_Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR NumDays = 14",
              "VAR RollingSum = ",
              "    CALCULATE([Total_Sales], ",
              "DATESINPERIOD(New_date[Date], LASTDATE(New_date[Date]), - NumDays, DAY))",
              "RETURN",
              "DIVIDE(RollingSum, NumDays)"
            ],
            "lineageTag": "5a8099bb-b159-4796-8677-73c981ac9e61"
          },
          {
            "name": "RollingAVG_Production",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR NumDays = 14",
              "VAR RollingSum = ",
              "    CALCULATE([Final Production], ",
              "DATESINPERIOD(New_date[Date], LASTDATE(New_date[Date]), - NumDays, DAY))",
              "RETURN",
              "DIVIDE(RollingSum, NumDays)"
            ],
            "lineageTag": "d44079f1-b362-4d7d-a970-0d089277acba"
          },
          {
            "name": "PY Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total_Sales], SAMEPERIODLASTYEAR(New_date[Date]))",
            "lineageTag": "553865bb-6138-4e57-a456-5ac575e5f468"
          },
          {
            "name": "PY Expense",
            "expression": "CALCULATE([Total Expense], SAMEPERIODLASTYEAR(New_date[Date]))",
            "formatString": "#,0.00",
            "lineageTag": "f67842e7-61fa-4c7c-9b5e-67a9f5603261"
          },
          {
            "name": "PY Final Production",
            "expression": "CALCULATE([Final Production], SAMEPERIODLASTYEAR(New_date[Date]))",
            "formatString": "0.00",
            "lineageTag": "ccb13b7d-84d0-4751-ba0a-a343451b3c4d"
          },
          {
            "name": "PY AVG Sales Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([AVG Sales Rate], SAMEPERIODLASTYEAR(New_date[Date]))",
            "lineageTag": "ab83e8fc-16cb-4d31-b778-6f46b905f9eb"
          },
          {
            "name": "PY AVG Production Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([AVG Production Rate], SAMEPERIODLASTYEAR(New_date[Date]))",
            "lineageTag": "8197ec3d-d60e-4fab-ac59-5317c456848a"
          },
          {
            "name": "PY Kacha Production",
            "expression": "CALCULATE([Kacha Production], SAMEPERIODLASTYEAR(New_date[Date]))",
            "formatString": "0.00",
            "lineageTag": "d9b1205e-390c-4dc2-8648-1721839ded3e"
          },
          {
            "name": "PY Kacha Load",
            "expression": "CALCULATE([Kacha Load], SAMEPERIODLASTYEAR(New_date[Date]))",
            "formatString": "0.00",
            "lineageTag": "6880df61-aae3-4e3b-b55d-747cf9c9f2fd"
          },
          {
            "name": "PY Kacha Load Loss",
            "expression": "CALCULATE([Kacha Load Loss], SAMEPERIODLASTYEAR(New_date[Date]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "71df4979-16f8-4a0a-aed9-8607263661f5"
          },
          {
            "name": "PY F_P %",
            "expression": "CALCULATE([Final Production %], SAMEPERIODLASTYEAR(New_date[Date]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a71407ce-ea86-4c27-ac5d-ab80967b982a"
          },
          {
            "name": "Production Diff",
            "expression": "[PY Final Production]/100 - [Final Production %]/100",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "40d59c2a-158d-4914-b517-afde7e30dc3d"
          }
        ],
        "partitions": [
          {
            "name": "_A Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "New_date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "420b9bbd418147faaf31146894dd767d"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "21786d57-99ef-4811-8149-2cc20ab0c526",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month_no",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH(New_date[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "cd07bbf4-b403-4d16-80cb-d0e5c417c085",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(New_date[Date], \"mmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "c19588ef-efbc-46ef-a2b3-a9e85532bf5f",
            "sortByColumn": "Fiscal_month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Fiscal_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF(New_date[Month_no]>10, New_date[Month_no]-10, New_date[Month_no]+10)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "3255f383-75be-4d8f-a018-4af039110237",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "FirstDayOfWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "New_date[Date] - WEEKDAY(New_date[Date], 2) + 1",
              ""
            ],
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "f51c4539-6933-408a-84a8-8c179dbd4206",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR CurrentMonth = MONTH(New_date[Date])",
              "VAR CurrentYear = YEAR(New_date[Date])",
              "VAR FiscalStartMonth = 11  // November is the start of the fiscal year",
              "RETURN",
              "IF(CurrentMonth >= FiscalStartMonth, \"Fy-\"&CurrentYear+1, \"Fy-\"&CurrentYear)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "374119af-5ea0-4c3c-8ad1-6f6dd8a096d8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "First day of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": "STARTOFMONTH(New_date[Date])",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "c79b5afd-cafe-409c-9f9b-3069aea994cc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "f0175d4b-9011-43c1-b174-30ffe35fde8a",
        "partitions": [
          {
            "name": "New_date",
            "mode": "import",
            "source": {
              "expression": "CALENDARAUTO(10)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ed9b1cc66c9f4a15a1147fa51de5b842"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "f77a7374-be26-44b1-95a6-a54c49c98f4b",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "5034b9c4-a7dc-4aaa-a4a7-edc81ac143f3",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "cbb83e81-502b-49b4-abaf-a3b1d9f5fc53",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "fbbdbf7d-8b92-4a75-a3e2-e494e0c90781",
        "partitions": [
          {
            "name": "Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Expense\", NAMEOF('_A Measures'[Total Expense]), 0),",
                "    (\"Sales\", NAMEOF('_A Measures'[Total_Sales]), 1),",
                "    (\"Production\", NAMEOF('_A Measures'[Final Production]), 2)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "SD_Name",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SD Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95c1b625-d46c-430f-9bcd-c901ef1861b2",
            "sourceColumn": "SD Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fbda6058-de88-4759-b3a8-5f563060221c",
        "partitions": [
          {
            "name": "SD_Name",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = AMB_Bricks_Expance_Sheet,",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Acc_Head] = \"SD_Payment\")),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\",{\"Payment To\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"Payment To\", \"SD Name\"}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Renamed Columns\",{{\"SD Name\", Text.Trim, type text}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Trimmed Text\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CY_PY_ParameterTable",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "eab4fb1901f44d4396485bd31de46306"
          }
        ],
        "columns": [
          {
            "name": "Metric",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "12fa8462-d7c6-499e-bf93-0e7e67fc4c63",
            "sourceColumn": "[Metric]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4666fa0d-f0eb-4297-8806-fd87d2d734c7",
            "sourceColumn": "[ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "b33d48eb-1149-4885-97fa-61b381235dae",
        "measures": [
          {
            "name": "CY_Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR SelectedMetric = SELECTEDVALUE(CY_PY_ParameterTable[ID])",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        SelectedMetric = 0, [Total Expense],    // Expense",
              "        SelectedMetric = 1, [Total_Sales],      // Sales",
              "        SelectedMetric = 2, [Final Production], // Production",
              "        BLANK()  // Fallback if no selection is made",
              "    )",
              ""
            ],
            "lineageTag": "a2b8f889-8605-4006-abf9-79e9577803d0"
          },
          {
            "name": "PY_Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR SelectedMetric = SELECTEDVALUE(CY_PY_ParameterTable[ID])",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        SelectedMetric = 0, [PY Expense],    // Prior Year Expense",
              "        SelectedMetric = 1, [PY Sales],      // Prior Year Sales",
              "        SelectedMetric = 2, [PY Final Production], // Prior Year Production",
              "        BLANK()  // Fallback if no selection is made",
              "    )",
              ""
            ],
            "lineageTag": "4908ce61-9c57-4b3e-b738-7f39f344ae13"
          }
        ],
        "partitions": [
          {
            "name": "CY_PY_ParameterTable",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DATATABLE(",
                "    \"Metric\", STRING, \"ID\", INTEGER,",
                "    {",
                "        {\"Expense\", 0},",
                "        {\"Sales\", 1},",
                "        {\"Production\", 2}",
                "    }",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}