table '_A Measures'
	lineageTag: ed28e673-3563-47e1-a6f0-b80f9d949ec9

	measure 'Total Expence' = SUM(AMB_Bricks_Expance_Sheet[Amount])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 39ce5621-388f-4414-83a9-251ea160ef06

	measure Coal_Expence = CALCULATE([Total Expence], AMB_Bricks_Expance_Sheet[Sub_Head]="Coal")
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 208f025b-98cf-462a-87bb-07acca3d4d79

	measure Sardar_Expence = CALCULATE([Total Expence], AMB_Bricks_Expance_Sheet[Acc_Head]= "SD_Payment")
		formatString: #,0
		lineageTag: 6b9b2b72-8a6d-4521-95c1-3413fdbe59f7

	measure 'Offical Cost' = CALCULATE([Total Expence], AMB_Bricks_Expance_Sheet[Acc_Head]="Offical Cost")
		formatString: #,0
		lineageTag: c7bdc014-0775-4076-8da2-4d9d6730494e

	measure Total_Sales = SUM(Vata_Sales[Final Price])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 91abb979-9473-4e75-8fee-2e3c819f2de2

	measure Profit = [Total_Sales]- [Total Expence]
		lineageTag: 7bce886d-6d1c-47d6-8c40-92cb624666f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Total_Production = SUM(Unload_table[Value])
		formatString: #,0
		lineageTag: 1b1644ee-0836-48cd-a8ac-1143aa581f35

	measure 'Unload %' =
			
			Var unload = [Total_Production]
			Var Total_unload = CALCULATE([Total_Production], ALLSELECTED(Unload_table[Attribute]))
			VAR Result = DIVIDE(unload, Total_unload,0)
			RETURN
			Result
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f0c905c7-6847-4709-94b7-ea464e236178

	measure Xcavator_Expence = CALCULATE([Total Expence], AMB_Bricks_Expance_Sheet[Acc_Head]="Xcavator")
		formatString: 0
		lineageTag: 75b6336d-72e5-423d-9eca-1b7f6e8fd7ca

	measure 'Sales %' =
			
			DIVIDE([Total_Sales],
			    CALCULATE([Total_Sales], All(Vata_Sales)),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 493f2e8b-fd50-4996-ae3f-72692dc960bd

	measure 'Unit Sold' = SUM(Vata_Sales[Actual Quantity])
		lineageTag: 4894f485-d141-4a3e-9d26-a3ff5c5d97df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Final Production' = SUM(Unload_table[Value])
		lineageTag: 81112a86-5724-4402-b9c7-e37124a97fa9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Production Rate' = DIVIDE([Total Expence],[Final Production],0)
		lineageTag: cd29d833-48d3-4ea1-914b-49d320a4ed2e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AVG Sales Rate' = DIVIDE([Total_Sales],[Unit Sold],0)
		lineageTag: 9b434768-12d6-42c6-91bc-03d017201611

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Xcavator hour' = CALCULATE(SUM(AMB_Bricks_Expance_Sheet[Quantity]), AMB_Bricks_Expance_Sheet[Sub_Head]="Driver Bill")
		formatString: 0
		lineageTag: b849a98b-bbae-40ab-b5fa-c21e20fbccca

	measure 'YTD Expense' =
			
			CALCULATE( [Total Expence],
			DATESYTD(New_date[Date],"10-31")
			)
		formatString: 0
		lineageTag: 144bf694-7373-44be-b6d4-63406d7b2ec2

	measure 'YTD Sales' =
			
			CALCULATE( [Total_Sales],
			DATESYTD(New_date[Date],"10-31")
			)
		lineageTag: f8c024f3-85eb-4f50-a48e-ff08982802bc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Production' = CALCULATE([Final Production], DATESYTD(New_date[Date],"10-31"))
		formatString: #,0
		lineageTag: 42d61cf2-7dee-47a3-9563-36a3dcbf8eae

	measure 'Previous Year YTD' =
			
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE(Parameter[Parameter Fields]) = "Expense", [PY Expence YTD],
			    SELECTEDVALUE(Parameter[Parameter Fields]) = "Sales", [PY Sales YTD],
			    SELECTEDVALUE(Parameter[Parameter Fields]) = "Production", [PY Production YTD],
			    BLANK()
			)
		lineageTag: 70edc807-fcc5-4fc5-8765-aec0e155f93d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PY Sales YTD' = ```
			
			CALCULATE(
			    [Total_Sales], 
			    DATESYTD(
			        SAMEPERIODLASTYEAR('Date'[Date])
			    )
			)
			
			```
		lineageTag: f776b16c-af3f-4ea4-ac75-25df2400d589

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PY Expence YTD' = ```
			
			CALCULATE(
			    [Total Expence], 
			    DATESYTD(
			        SAMEPERIODLASTYEAR('Date'[Date])
			    )
			)
			```
		formatString: 0
		lineageTag: ab08a153-2bb5-46aa-a42c-44b4b2e76d89

	measure 'PY Production YTD' = ```
			
			CALCULATE(
			    [Final Production], 
			    DATESYTD(
			        SAMEPERIODLASTYEAR('Date'[Date])
			    )
			)
			```
		formatString: 0
		lineageTag: 01c1e14f-2be5-4be6-9564-c53a29819ccf

	measure Labour_Cost = CALCULATE([Total Expence], AMB_Bricks_Expance_Sheet[Acc_Head]="Labour")
		formatString: #,0
		lineageTag: 1259a630-c016-4c82-abf1-6f1c476fb9ae

	measure Advance_23-24 = CALCULATE([Sardar_Expence], AMB_Bricks_Expance_Sheet[Payment_for]="Advance for 2023-24")
		formatString: 0
		lineageTag: 358701a0-24f9-47c3-8eb9-d6d5e7f145e1

	measure 'Total Kacha Production' = CALCULATE(SUM(Kacha_Load_Sheet[Production_Amount]), Kacha_Load_Sheet[Production_Category]="Kacha")
		formatString: #,0
		lineageTag: d23bd4ad-04d7-4143-aea3-6c6415b7a875

	measure 'Total Paka Add' = CALCULATE(SUM(Kacha_Load_Sheet[Production_Amount]), Kacha_Load_Sheet[Production_Category]="Paka_Add")
		formatString: 0
		lineageTag: 12ceec11-ca71-4d25-a01a-a20e38404117

	measure 'Kacha Load' = CALCULATE(SUM(Kacha_Load_Sheet[Production_Amount]), Kacha_Load_Sheet[Production_Category]="Load")
		formatString: 0
		lineageTag: 6e42e8e3-08f3-4918-9800-c78a8f501a53

	measure '% of Load' = DIVIDE([Kacha Load],[Total Kacha Production], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3f715120-54cd-4e80-9eaa-67b6e0d5b1c4

	measure 'Kacha Production Expense' = CALCULATE([Total Expence], AMB_Bricks_Expance_Sheet[Sub_Head] in {"Kacha_Production"})
		formatString: #,0
		lineageTag: 77b016dc-7e31-4c1d-aa32-2e3e07f97027

	measure 'Per 1K Kacha Production' = DIVIDE([Kacha Production Expense], [Total Kacha Production], 0)*1000
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d6de3202-b9fc-4770-a15b-9f59dadac806

	measure 'Guage Target Total Load' = [Kacha Load] + 300000
		formatString: 0
		lineageTag: da33d8dd-730c-453b-91bb-31e0ff2f0132

	measure 'Guage Maximum' = [Guage Target Total Load]*1.15
		lineageTag: 41c74bc9-899b-490f-a7e0-4c68f2cca85b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Load Expense' = CALCULATE([Total Expence], AMB_Bricks_Expance_Sheet[Sub_Head]="Load")
		formatString: 0
		lineageTag: 332612e9-0f29-42f7-8cb1-3031edd8a9d7

	measure 'Per 1K Load Expense' = DIVIDE( [Load Expense], [Guage Target Total Load])* 1000
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0d67e0c1-1a97-43a2-bff8-64e7141cc7f6

	measure 'Unload Cost' = CALCULATE([Total Expence], AMB_Bricks_Expance_Sheet[Sub_Head]="Unload")
		formatString: 0
		lineageTag: 314a2844-72e0-4e43-9f27-8037a6838e2b

	measure 'Per 1K Unload Expense' = DIVIDE([Unload Cost],[Final Production],0) * 1000
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 627b8ba6-169b-415d-8876-e0af567f4fb9

	partition '_A Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

