table AMB_Bricks_Expance_Sheet
	lineageTag: cda9d48b-efea-4726-883d-79b0141d6ec0

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 259140b5-efde-4267-b5e8-5d658da6d6cc
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Receipt No'
		dataType: int64
		formatString: 0
		lineageTag: 28a7b5f5-ab76-47f8-af5b-93d76617c7c2
		summarizeBy: sum
		sourceColumn: Receipt No

		annotation SummarizationSetBy = Automatic

	column Acc_Head
		dataType: string
		lineageTag: 49b43ec2-6dda-4a89-92d9-34021a4b55f7
		summarizeBy: none
		sourceColumn: Acc_Head

		annotation SummarizationSetBy = Automatic

	column Sub_Head
		dataType: string
		lineageTag: b035c74e-c538-4f83-a0e8-c204eca49f54
		summarizeBy: none
		sourceColumn: Sub_Head

		annotation SummarizationSetBy = Automatic

	column Payment_for
		dataType: string
		lineageTag: 5c3b0863-a836-4867-89d8-9141ef8f3909
		summarizeBy: none
		sourceColumn: Payment_for

		annotation SummarizationSetBy = Automatic

	column 'Payment To'
		dataType: string
		lineageTag: 73cdb21c-a887-4e2f-9501-4213f6734617
		summarizeBy: none
		sourceColumn: Payment To

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 5c68c787-6e80-437d-aa3c-e614c5325b2d
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: int64
		formatString: #,0
		lineageTag: 88838f0d-3589-4990-a693-ce0aca600a33
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: 028de10c-b746-43f1-89f5-eca3c477b01e
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = Automatic

	partition AMB_Bricks_Expance_Sheet = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("H:\_Portfolio Project Github\BrickField-Sales-Cost-Tracking-Dashboard\AMB_Vata23_24.xlsx"), null, true),
				    AMB_Bricks_Expance_Sheet_Table = Source{[Item="AMB_Bricks_Expance_Sheet",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(AMB_Bricks_Expance_Sheet_Table,{{"Date", type date}, {"Receipt No", Int64.Type}, {"Acc_Head", type text}, {"Sub_Head", type text}, {"Payment_for", type any}, {"Payment To", type any}, {"Quantity", type any}, {"Amount", type any}, {"Remarks", type any}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Amount] <> null)),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows",{{"Amount", Int64.Type}, {"Date", type date}, {"Quantity", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

