table Date
	lineageTag: 19d73e2f-9c30-497b-8454-919a1f7dadac
	dataCategory: Time

	measure _ShowValueForDates =
			
			VAR __LastDateWithData =
			    CALCULATE (
			        MAXX ( { MAX ( 'AMB_Bricks_Expance_Sheet'[Date] ), MAX ( 'Kacha_Load_Sheet'[Date] ), MAX ( 'Unload_table'[Date] ), MAX ( 'Vata_Sales'[Date] ) }, ''[Value] ),
			        REMOVEFILTERS ()
			    )
			VAR __FirstDateVisible =
			    MIN ( 'Date'[Date] )
			VAR __Result =
			    __FirstDateVisible <= __LastDateWithData
			RETURN
			    __Result
		isHidden
		displayFolder: Hidden Time Intelligence
		lineageTag: 4302a623-367a-419c-adbc-550e57e0dd7c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Monthly

		annotation SQLBI_CalendarType = Fiscal

	column Date
		dataType: dateTime
		isKey
		formatString: m/d/yyyy
		lineageTag: 01ff817e-20b5-4c36-87b1-c6b5703c9a14
		dataCategory: PaddedDateTableDates
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Date]

		annotation SQLBI_AttributeTypes = Date, FiscalDate

	column DateKey
		dataType: int64
		isHidden
		lineageTag: 8ec9830c-a1b1-4776-bf73-2ffc9ce9b1a2
		summarizeBy: count
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[DateKey]

		annotation SummarizationSetBy = Automatic

	column 'Sequential Day Number'
		dataType: int64
		isHidden
		lineageTag: 082ffc1b-d84f-4ab0-bd33-286d5a9d5277
		summarizeBy: sum
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Sequential Day Number]

		annotation SQLBI_AttributeTypes = ManufacturingDate

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: string
		lineageTag: 60eceeab-d054-4f1d-9800-1d88e6924276
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Year Month]
		sortByColumn: 'Year Month Number'

	column 'Year Month Number'
		dataType: int64
		isHidden
		lineageTag: f6106283-f77e-4e24-84be-ea0d2439fdbb
		dataCategory: Months
		summarizeBy: sum
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Year Month Number]

		annotation SQLBI_AttributeTypes = FiscalMonths

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: db83b17f-1675-4fd9-b783-d4a5c0738aac
		dataCategory: Years
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Fiscal Year]
		sortByColumn: 'Fiscal Year Number'

	column 'Fiscal Year Number'
		dataType: int64
		isHidden
		lineageTag: ca09459b-f24a-4494-9fd6-ad028465e0ba
		dataCategory: Years
		summarizeBy: sum
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Fiscal Year Number]

		annotation SQLBI_AttributeTypes = FiscalYears

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Quarter'
		dataType: string
		lineageTag: 67385ea8-d20a-4118-8e93-99610b7a601c
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Fiscal Year Quarter]
		sortByColumn: 'Fiscal Year Quarter Number'

	column 'Fiscal Year Quarter Number'
		dataType: int64
		isHidden
		lineageTag: 21f6b450-c144-4a5f-a1b5-51de50fc06a2
		dataCategory: Quarters
		summarizeBy: sum
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Fiscal Year Quarter Number]

		annotation SQLBI_AttributeTypes = FiscalQuarters

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: string
		lineageTag: cf9bc231-e28c-4741-97ff-59d82a881669
		dataCategory: QuarterOfYear
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Fiscal Quarter]

	column Month
		dataType: string
		lineageTag: 94876f89-1fdd-43a4-a3fc-fa98ef0649a6
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Month]
		sortByColumn: 'Fiscal Month Number'

	column 'Fiscal Month Number'
		dataType: int64
		isHidden
		lineageTag: 9f1b5f18-7799-40bb-9187-8623d124be1f
		dataCategory: MonthOfYear
		summarizeBy: sum
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Fiscal Month Number]

		annotation SQLBI_AttributeTypes = FiscalMonthOfYear

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month in Quarter Number'
		dataType: int64
		isHidden
		lineageTag: b4819b45-fb98-4c35-8f1b-f82756a372ed
		dataCategory: MonthOfQuarter
		summarizeBy: sum
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Fiscal Month in Quarter Number]

		annotation SQLBI_AttributeTypes = FiscalMonthOfQuarter

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: string
		lineageTag: 7e551afb-4a59-40bc-98cd-a9d598df2a18
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Day of Week]
		sortByColumn: 'Day of Week Number'

		annotation SQLBI_AttributeTypes = FiscalDayOfWeek

		annotation SQLBI_FilterSafe = True

	column 'Day of Week Number'
		dataType: int64
		isHidden
		lineageTag: 0e9c5a2e-9317-41b0-b113-919e716df45f
		dataCategory: DayOfWeek
		summarizeBy: sum
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Day of Week Number]

		annotation SQLBI_AttributeTypes = FiscalDayOfWeek

		annotation SQLBI_FilterSafe = True

		annotation SummarizationSetBy = Automatic

	column 'Day of Month Number'
		dataType: int64
		isHidden
		lineageTag: 8c8d619c-aa98-46e9-a62f-46e844408ea9
		dataCategory: DayOfMonth
		summarizeBy: sum
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Day of Month Number]

		annotation SQLBI_AttributeTypes = FiscalDayOfMonth

		annotation SummarizationSetBy = Automatic

	column 'Day of Fiscal Year Number'
		dataType: int64
		isHidden
		lineageTag: 25cd5bf2-95be-402c-8b5a-739d735efbae
		dataCategory: DayOfYear
		summarizeBy: sum
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Day of Fiscal Year Number]

		annotation SQLBI_AttributeTypes = FiscalDayOfYear

		annotation SummarizationSetBy = Automatic

	column DateWithTransactions
		dataType: boolean
		isHidden
		lineageTag: c32c0893-a596-4953-920e-4230ee55b782
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[DateWithTransactions]

		annotation SQLBI_AttributeTypes = DateDuration

	hierarchy Fiscal
		lineageTag: 9e9c7c01-89c9-4c0b-b52d-f0df5c92911b

		level Year
			lineageTag: b21db779-0218-46e6-bcc4-62a1e0262ed3
			column: 'Fiscal Year'

		level Quarter
			lineageTag: d80a9d7c-2503-4f6f-affa-77eca9acb6d9
			column: 'Fiscal Year Quarter'

		level Month
			lineageTag: d059ef4c-5046-4ab1-ac08-4958f82fe1a1
			column: 'Year Month'

	partition Date = calculated
		mode: import
		source = DateAutoTemplate

	annotation SQLBI_Template = Dates

	annotation SQLBI_TemplateTable = Date

	annotation SQLBI_CalendarType = Fiscal

