table Kacha_Load_Sheet
	lineageTag: 92edcda6-5fa0-41d0-86c5-eb2f5bbc7c6b

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c669c26c-1b21-408a-9ffb-f7398f5cd5a4
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Production_Category
		dataType: string
		lineageTag: 5451e7f2-a4f6-448a-b78b-fb952d8a51a5
		summarizeBy: none
		sourceColumn: Production_Category

		annotation SummarizationSetBy = Automatic

	column Sardar_name
		dataType: string
		lineageTag: 1ad3c0c7-ad1e-4398-b696-11d91e91b8ed
		summarizeBy: none
		sourceColumn: Sardar_name

		annotation SummarizationSetBy = Automatic

	column Production_Amount
		dataType: int64
		formatString: 0
		lineageTag: a28d25f9-b52c-4b01-a11c-78a9c070b401
		summarizeBy: sum
		sourceColumn: Production_Amount

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: 562fff88-bca0-4e41-b2cb-9325ce61edae
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = Automatic

	partition Kacha_Load_Sheet = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("H:\_Portfolio Project Github\BrickField-Sales-Cost-Tracking-Dashboard\AMB_Vata23_24.xlsx"), null, true),
				    Kacha_Load_Sheet_Table = Source{[Item="Kacha_Load_Sheet",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Kacha_Load_Sheet_Table,{{"Date", type date}, {"Production_Category", type text}, {"Sardar_name", type text}, {"Production_Amount", Int64.Type}, {"Remarks", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

